# **Guided Lab - 343.2.1 - NumPy Random module - Random Number Generation**

## **Lab Overview:**

In this lab, we will explore the functionality of several important random number generation functions provided by the NumPy library in Python. These functions include `np.random.choice()` for generating random samples from `arrays`, `np.random.shuffle() for shuffling the contents of arrays, and `np.random.randn()` for generating random numbers from a standard normal distribution. Through hands-on exercises, participants will gain a understanding of how to use these functions effectively in various scenarios.

## **Lab Objective:**

By the end of this lab, participants will:

- Describe the purpose and the usage of key random number generation functions provided by NumPy, including np.random.choice(), np.random.shuffle(), and np.random.randn().
- Demonstrate how to generate random samples from arrays, shuffle array contents, and generate random numbers from a standard normal distribution.


## **Introduction**
The syntax of `np.random.randn()` typically involves passing the desired dimensions of the array as arguments. For example:

```np.random.randn() - generates a single random number```

```np.random.randn(n) - generates an array of n random numbers.```

``` np.random.randn(m, n) - generates a 2D array with m rows and n columns of random numbers.```

Note: These random numbers are will be drawn from a standard normal distribution, where the mean is 0 and the standard deviation is 1.






## **Example 1: Generates a single random number.**

in this example we will generate a single random number by using the random() function. The random() function returns a random number within the range of 0 to 1.0.

In [12]:
import numpy as np
from numpy import random

# 10 random floats between 0 and 1
data = random.rand(10) 
print("Random number sampled from a standard normal distribution:",data)
print()

# 7 random integers between 0 and 5, returns one integer without arguments, size specifies the shape of an array
data2 = random.randint(5, size=(7)) 
print("Random number sampled from a standard normal distribution:\n",data2, 42)

data3 = random.randint(5, size=(3, 4)) 
print("Random number sampled from a standard normal distribution:\n",data3)

Random number sampled from a standard normal distribution: [0.10108953 0.24906625 0.79648364 0.58939269 0.99779708 0.57535609
 0.58763224 0.29679178 0.42867092 0.92937507]

Random number sampled from a standard normal distribution:
 [1 2 0 0 3 1 2] 42
Random number sampled from a standard normal distribution:
 [[1 1 2 1]
 [0 4 0 0]
 [4 1 0 2]]


## **Example 2: Generates an array of n random numbers.**
In this example, we generate an array of n random numbers by using the `np.random.randn(n)` function. The function returns an array of n random numbers with mean 0 and standard deviation 1.


In [13]:
n = 5
random_numbers = random.randn(n)
print("Array of", n, "random numbers sampled from a standard normal distribution:")
print(random_numbers)


Array of 5 random numbers sampled from a standard normal distribution:
[ 1.74597212 -0.04976857 -0.81894081 -0.71959882  0.36540445]


## **Example 3: Generates a 2D array with m rows and n columns of random numbers.**

In this example, we will generate a 2D array with 3 rows and 4 columns of random numbers. The result will be a 3x4 2D array with random numbers ranging from 0 to 99.    

In [16]:
m = 3
n = 2
random_numbers_2d = random.randn(m, n)
print("2D array of random numbers sampled from a standard normal distribution (", m, "rows x", n, "columns):")
print(random_numbers_2d)

m1 = 4
n1 = 2
random_numbers2_2d = random.randn(m1, n1)
print("2D array of random numbers sampled from a standard normal distribution (", m1, "rows x", n1, "columns):\n", random_numbers2_2d)

2D array of random numbers sampled from a standard normal distribution ( 3 rows x 2 columns):
[[-0.76477598  0.19917108]
 [-0.99037421  0.98610926]
 [ 0.25248891  0.12892551]]
2D array of random numbers sampled from a standard normal distribution ( 4 rows x 2 columns):
 [[0.29538017 0.86670919]
 [0.21590136 0.02381745]
 [0.58687493 1.24131465]
 [0.06618132 0.78091248]]


## **Example 4: Generates a random sample from a given 1-D array.**
In this example, we will generate a random sample from a given 1-D array. We will use the numpy.random.choice() function to do this.

In [ ]:
from numpy import random

# Define an array of elements
elements = ['a', 'b', 'c', 'd', 'e']

# Generate a random sample from the array
random_sample = random.choice(elements)
print("Randomly sampled element:", random_sample)

# The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.
# The probability of 'b' and 'd' are .5 and .4, use size to specify the array shape
random_sample_2 = random.choice(elements, p=[0.0, 0.5, 0.0, 0.4, 0.1], size=(10))
print("Randomly sampled element:", random_sample_2)


Randomly sampled element: c
Randomly sampled element: ['b' 'b' 'b' 'b' 'd' 'd' 'd' 'd' 'd' 'd']


## **Example 5: Shuffles the contents of an array in place.**
In this example, we will shuffle the contents of an array. We will use the np.random.shuffle() function.

In [ ]:
# Define an array of elements
elements = ['a', 'b', 'c', 'd', 'e']

# Shuffle the array in place
random.shuffle(elements)
print("Shuffled array:", elements)


Shuffled array: ['e', 'c', 'a', 'd', 'b']


## **Example 6: Real world example -Restauran**t Menu Randomizer

Suppose you're designing a digital menu for a restaurant, and you want to create a feature that suggests a random dish to the user when they're undecided about what to order. You can use the random module to implement this feature.

In [ ]:
# Define a list of dishes on the menu
menu = [
    "Spaghetti Carbonara",
    "Chicken Alfredo",
    "Margherita Pizza",
    "Cheeseburger",
    "Caesar Salad",
    "Fish and Chips",
    "Pad Thai",
    "Sushi Platter",
    "Vegetable Stir-Fry",
    "Grilled Salmon"
]

# Function to suggest a random dish
def suggest_dish():
    random_dish = random.choice(menu)
    return random_dish

# Main program
print("Welcome to the Restaurant Menu Randomizer!\n")
print("If you're undecided about what to order, let us help you decide.\n")

while True:
    user_input = input("Press enter to get a random dish suggestion (or type 'quit' to exit): \n")

    if user_input.lower() == 'quit':
        print("Thank you for using the Restaurant Menu Randomizer. Enjoy your meal!")
        break

    suggested_dish = suggest_dish()
    print("Randomly suggested dish:", suggested_dish, "\n")


Welcome to the Restaurant Menu Randomizer!

If you're undecided about what to order, let us help you decide.



Randomly suggested dish: Sushi Platter 

Randomly suggested dish: Pad Thai 

Randomly suggested dish: Grilled Salmon 

Randomly suggested dish: Margherita Pizza 


Thank you for using the Restaurant Menu Randomizer. Enjoy your meal!
