## Task 1: Data Type Objects
1. Create a NumPy array using np.array() function and specify the data type as 'int32.' Print the array and its data type.
1. Create another NumPy array using np.array() with the data type as 'float64.' Print the array and its data type.

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7], dtype='int32')
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7]
int32


## Task 2: One-Dimensional and Multi-Dimensional Arrays
1. Create a one-dimensional NumPy array containing the integers from 1 to 5. Print the array.
1. Create a two-dimensional NumPy array (matrix) with the following values:

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[6, 7, 8, 9], [10, 11, 12, 13]])
print(arr_2d)

[1 2 3 4 5]
[[ 6  7  8  9]
 [10 11 12 13]]


## Task 3: NumPy Operations
1. Create two NumPy arrays arr1 and arr2 with any values of your choice. Perform element-wise addition, subtraction, multiplication, and division between these arrays and print the results.
1. Calculate the dot product between arr1 and arr2. Print the result.
1. Use NumPy to calculate the mean, median, and standard deviation of arr1.

In [7]:
arr1 = np.array([2, 4, 6, 8])
arr2 = np.array([10, 12, 14, 16])

add_arr1 = arr1 + 2
sub_arr1 = arr1 - 1
mult_arr1 = arr1 * 10
div_arr1 = arr1 / 2
dot_arr1 = np.dot(arr1, arr2)
mean_arr1 = np.mean(arr1)
median_arr1 = np.median(arr1)
std_arr1 = np.std(arr1)

print("Addition: \n", add_arr1, "\nSubtraction:\n", sub_arr1, "\nMultiplication:\n", mult_arr1, "\nDivision:\n", div_arr1)
print("\nDot product:\n", dot_arr1)
print("\nMean:\n", mean_arr1, "\nMedian:\n", median_arr1, "\nStandard Deviation:\n", std_arr1)

add_arr2 = arr2 + 2
sub_arr2 = arr2 - 1
mult_arr2 = arr2 * 10
div_arr2 = arr2 / 2
dot_arr2 = np.dot(arr1, arr2)
mean_arr2 = np.mean(arr2)
median_arr2 = np.median(arr2)
std_arr2 = np.std(arr2)

print("\nAddition: \n", add_arr2, "\nSubtraction:\n", sub_arr2, "\nMultiplication:\n", mult_arr2, "\nDivision:\n", div_arr2)
print("\nDot product:\n", dot_arr2)
print("\nMean:\n", mean_arr2, "\nMedian:\n", median_arr2, "\nStandard Deviation:\n", std_arr2)

Addition: 
 [ 4  6  8 10] 
Subtraction:
 [1 3 5 7] 
Multiplication:
 [20 40 60 80] 
Division:
 [1. 2. 3. 4.]

Dot product:
 280

Mean:
 5.0 
Median:
 5.0 
Standard Deviation:
 2.23606797749979

Addition: 
 [12 14 16 18] 
Subtraction:
 [ 9 11 13 15] 
Multiplication:
 [100 120 140 160] 
Division:
 [5. 6. 7. 8.]

Dot product:
 280

Mean:
 13.0 
Median:
 13.0 
Standard Deviation:
 2.23606797749979
